---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: default
spec:
  dependsOn:
    - name: infra-configs
  interval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-sync
    namespace: flux-system
  path: ./apps/prod
  prune: true
  wait: true