apiVersion: v1
kind: Pod
metadata:
  labels:
    app: n8n
  name: n8n
  namespace: n8n
spec:
  containers:
  - image: docker.n8n.io/n8nio/n8n
    name: n8n
    env:
      - name: WEBHOOK_URL
        value: https://n8n.dev.cbxon.co.uk/
      - name: NGN_HOST
        value: n8n.dev.cbxon.co.uk
      - name: NGN_PORT
        value: "5678"
    ports:
    - containerPort: 5678
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
