---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: default
spec:
  wait: true
  interval: 30s
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-sync
    namespace: flux-system
  path: "./kustomizations/infrastructure/"
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: applications
  namespace: default
spec:
  dependsOn:
    - name: infrastructure
  wait: true
  interval: 30s
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-sync
    namespace: flux-system
  path: "./kustomizations/applications/"
  prune: true