---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: default
spec:
  targetNamespace: flux-system
  interval: 1h
  release-name: sealed-secrets-controller
  install:
    crds: CreateReplace
  chart:
    spec:
      chart: sealed-secrets
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: default
      interval: 10m
