apiVersion: v1
kind: Pod
metadata:
  labels:
    run: bitmagnet
  name: bitmagnet
  namespace: bitmagnet
spec:
  containers:
  - image: postgres
    name: bitmagnet-postgres
    ports:
      - containerPort: 5432
    env:
      - name: POSTGRES_PASSWORD
        value: postgres
      - name: POSTGRES_DB
        value: bitmagnet
      - name: PGUSER
        value: postgres
  - image: ghcr.io/bitmagnet-io/bitmagnet:latest
    name: bitmagnet
    env:
      - name: POSTGRES_HOST
        value: 127.0.0.1
      - name: POSTGRES_PASSWORD
        value: postgres
    args:
      - worker
      - run
      - --keys=http_server
      - --keys=queue_server
      - --keys=dht_crawler
    ports:
    - containerPort: 3333
    - containerPort: 3334
    - containerPort: 3334
      protocol: UDP
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
