apiVersion: v1
kind: Pod
metadata:
  labels:
    run: bitmagnet
  name: bitmagnet
  namespace: bitmagnet
spec:
  containers:
  - image: ghcr.io/bitmagnet-io/bitmagnet:latest
    name: bitmagnet
    env:
      - name: POSTGRES_HOST
        value: postgres
      - name: POSTGRES_PASSWORD
        value: postgres
    command:
      - worker
      - run
      - --keys=http_server
      - --keys=queue_server
      - --keys=dht_crawler
    ports:
    - containerPort: 3333
    - containerPort: 3334
    - containerPort: 3334
      protocol: UDP
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
