---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-smb
  namespace: default
spec:
  install:
    createNamespace: true
  targetNamespace: kube-system
  interval: 10m
  chart:
    spec:
      chart: csi-driver-smb
      version: v1.18.0
      sourceRef:
        kind: HelmRepository
        name: csi-driver-smb
        namespace: default
      interval: 10m
