---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-base
  namespace: default
spec:
  install:
    createNamespace: true
  targetNamespace: istio-system
  interval: 10m
  chart:
    spec:
      chart: base
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: default
      interval: 10m
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-cni
  namespace: default
spec:
  install:
    createNamespace: true
  targetNamespace: istio-system
  interval: 10m
  chart:
    spec:
      chart: cni
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: default
      interval: 10m
  dependsOn:
    - name: istio-base
  values:
    cniBinDir: /var/lib/rancher/k3s/data/current/bin/
    cniConfDir: /var/lib/rancher/k3s/agent/etc/cni/net.d
    global:
      platform: k3s
    profile: ambient
    logLevel: info
    excludeNamespaces:
      - istio-system
      - kube-system
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-istiod
  namespace: default
spec:
  install:
    createNamespace: true
  targetNamespace: istio-system
  interval: 10m
  chart:
    spec:
      chart: istiod
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: default
      interval: 10m
  dependsOn:
    - name: istio-base
    - name: istio-cni
  values:
    profile: ambient
    global:
      cni:
        enabled: true
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-ztunnel
  namespace: default
spec:
  install:
    createNamespace: true
  targetNamespace: istio-system
  interval: 10m
  chart:
    spec:
      chart: ztunnel
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: default
      interval: 10m
  dependsOn:
    - name: istio-base
    - name: istio-cni
    - name: istio-istiod
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-egressgateway
  namespace: default
spec:
  install:
    createNamespace: true
  targetNamespace: istio-system
  interval: 10m
  chart:
    spec:
      chart: gateway
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: default
      interval: 10m
  dependsOn:
    - name: istio-base
    - name: istio-cni
    - name: istio-istiod
  values:
    name: "istio-egressgateway"
    service:
      type: ClusterIP