---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: default
spec:
  install:
    createNamespace: true
  targetNamespace: metallb-system
  interval: 10m
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: default
      interval: 10m
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: talos-control-plane-pool
  namespace: metallb-system
spec:
  addresses:
    - $(IP_ADDRESS_RANGE)
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: talos-l2advertisement
  namespace: metallb-system